-- 1. 유저 포인트 테이블 생성
CREATE TABLE profiles (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  nickname TEXT,
  points INTEGER DEFAULT 0,
  accepted_answers INTEGER DEFAULT 0,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 유저 회원가입 시 프로필 자동 생성 트리거 (필요 시)
-- CREATE OR REPLACE FUNCTION public.handle_new_user()
-- RETURNS trigger AS $$
-- BEGIN
--   INSERT INTO public.profiles (id, nickname, points)
--   VALUES (new.id, new.raw_user_meta_data->>'nickname', 0);
--   RETURN new;
-- END;
-- $$ LANGUAGE plpgsql SECURITY DEFINER;
-- CREATE TRIGGER on_auth_user_created
--   AFTER INSERT ON auth.users
--   FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 2. 답변(댓글) 테이블 생성
CREATE TABLE comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
  author_id UUID REFERENCES auth.users(id) NOT NULL,
  nickname TEXT,
  content TEXT NOT NULL,
  is_accepted BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. posts 테이블에 채택 상태 추가
ALTER TABLE posts ADD COLUMN IF NOT EXISTS is_resolved BOOLEAN DEFAULT FALSE;

-- 4. 답변 채택 시 포인트 지급 함수 (RPC)
CREATE OR REPLACE FUNCTION accept_answer(p_post_id BIGINT, p_comment_id BIGINT, p_answer_author_id UUID)
RETURNS void AS $$
BEGIN
  -- 1. 답변 채택 상태 변경
  UPDATE comments SET is_accepted = TRUE WHERE id = p_comment_id;
  
  -- 2. 게시글 해결 상태 변경
  UPDATE posts SET is_resolved = TRUE WHERE id = p_post_id;
  
  -- 3. 답변 작성자 포인트 증가 (+4) 및 채택 수 증가
  INSERT INTO profiles (id, points, accepted_answers)
  VALUES (p_answer_author_id, 4, 1)
  ON CONFLICT (id) DO UPDATE
  SET points = profiles.points + 4,
      accepted_answers = profiles.accepted_answers + 1;
END;
$$ LANGUAGE plpgsql;
