-- 1. 게시글 저장 테이블 (posts) 생성
CREATE TABLE posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  author_id UUID REFERENCES auth.users(id) NOT NULL,
  author_email TEXT,
  nickname TEXT,
  book_title TEXT NOT NULL,
  category TEXT DEFAULT '일반',
  views BIGINT DEFAULT 0
);

-- 2. 조회수 증가를 위한 함수 (RPC) 생성
CREATE OR REPLACE FUNCTION increment_views(post_id BIGINT)
RETURNS void AS $$
BEGIN
  UPDATE posts
  SET views = views + 1
  WHERE id = post_id;
END;
$$ LANGUAGE plpgsql;

-- 3. 보안 설정 (Row Level Security - RLS)
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;

-- 모든 사용자에게 읽기 권한 허용
CREATE POLICY "Anyone can read posts" ON posts
  FOR SELECT USING (true);

-- 로그인한 사용자에게만 쓰기 권한 허용
CREATE POLICY "Authenticated users can insert posts" ON posts
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- 본인 게시글만 수정 가능
CREATE POLICY "Users can update their own posts" ON posts
  FOR UPDATE USING (auth.uid() = author_id);
